name: Deploy to Server (DISABLED)

on:
  workflow_dispatch:  # Manual trigger only

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Run basic syntax check
      run: node -c server.js
      
    - name: Deploy to server via webhook
      run: |
        echo "🚀 Triggering deployment..."
        
        # Try multiple potential deployment URLs
        DEPLOY_URLS=(
          "https://joinkfacrawler.onrender.com/deploy"
          "http://your-server-ip:3000/deploy"
        )
        
        for url in "${DEPLOY_URLS[@]}"; do
          echo "Attempting deployment to: $url"
          
          # Try deployment with hardcoded token first
          response=$(curl -s -w "\\n%{http_code}" -X POST "$url" \
            -H "Content-Type: application/json" \
            -H "x-deploy-token: breadbro" \
            -d '{"source": "github-actions", "commit": "${{ github.sha }}", "ref": "${{ github.ref }}"}' \
            --connect-timeout 10 \
            --max-time 30 \
            2>/dev/null || echo "connection_failed\\n000")
          
          http_code=$(echo "$response" | tail -n1)
          response_body=$(echo "$response" | head -n -1)
          
          echo "Response: $response_body"
          echo "HTTP Code: $http_code"
          
          if [ "$http_code" = "200" ]; then
            echo "✅ Deployment successful to $url!"
            exit 0
          else
            echo "❌ Deployment failed to $url (HTTP $http_code)"
          fi
        done
        
        echo "⚠️ All deployment attempts failed, but not failing the workflow"
        echo "The server will automatically update from git on next restart" 